Execute files that are hooked in correctly. Closes #181

diff --git a/vv b/vv
--- a/vv
+++ b/vv
@@ -539,7 +539,7 @@ init_vv_hooks() {
 }
 
 run_hook() {
-	hook "$1" "$2" "$3" "$4"
+	hook "$@"
 }
 hook() {
 	# Display all hooks to screen if the show_hooks flag is set
@@ -547,7 +547,30 @@ hook() {
 		echo "${magenta}[Hook]${normal}" "$1" "$2" "$3" "$4"
 	fi
 
-	test -f "$vv_scripts_folder""$1" && source "$vv_scripts_folder""$1" && which run_"$1" &&  run_"$1" "$2" "$3" "$4"
+	if [[ -f "$vv_scripts_folder""$1"   ]]; then
+		cd "$vv_scripts_folder" || echo "Could not change directory."
+		script_type="$(head -n 1 "$1")"
+		case "$script_type" in
+			*bash*)
+				bash "$1" "$2" "$3" "$4"
+			;;
+			*php*)
+				php "$1" "$2" "$3" "$4"
+			;;
+			*python*)
+				python "$1" "$2" "$3" "$4"
+			;;
+			*node*)
+				node "$1" "$2" "$3" "$4"
+			;;
+			*ruby*)
+				ruby "$1" "$2" "$3" "$4"
+			;;
+			*)
+				error "Could not parse file hooked into $1"
+			;;
+		esac
+	fi
 	# test -f "$vv_scripts_folder"hooks && source "$vv_scripts_folder"hooks && which "$1" && $("$1" "$2")
 	# this is currently not working
 }
